languageCode: en-us
defaultContentLanguage: en
theme: "ahmt-me-cupper"
enableGitInfo: true
social:
  twitter: ahaltindis

languages:
  en:
    baseURL: https://en.ahmt.me
    languageName: English
    weight: 1
    contentDir: content/en
    title: 'Ahmet Altindis'
    params:
      navTitleText: 'Ahmet Altindis'
      description: some blog, some photograps, and a bit projects so on.
      homeMetaContent: Ahmet Altindis - Software Engineer. Maker, hacker, coder, learner, reader, photographer.
    pagination:
      path: page
    menu:
      nav:
        - identifier: home
          name: Hello 👋
          url: /
          weight: 1
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 2
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 3
        - identifier: til
          name: Today-I-Learned
          url: /til/
          weight: 4
        # - identifier: dict
        #   name: Dictionary
        #   url: /dict/
        #   weight: 4
        - identifier: photographs
          name: Photographs
          url: /photographs/
          weight: 5
        # - identifier: links
        #   name: Bookmarks
        #   url: /links/
        #   weight: 6
        # - identifier: tags
        #   name: Tags
        #   url: /tags/
        #   weight: 7
        - identifier: rss
          name: RSS
          url: /index.xml
          weight: 8
    permalinks:
      photographs: "photo-:filename/"
      til: "til-:filename/"
      projects: "project-:filename/"
  tr:
    baseURL: https://tr.ahmt.me
    languageName: Türkçe
    languageCode: tr-TR
    weight: 2
    contentDir: content/tr
    title: 'Ahmet Altındiş'
    params:
      navTitleText: 'Ahmet Altındiş'
      description: biraz yazı, biraz fotoğraf, biraz da projeler falan.
      homeMetaContent: Ahmet Altındiş - Yazılım geliştirici. Biraz yazı, biraz fotoğraf, biraz da projeler falan.
    pagination:
      path: sayfa
    menu:
      nav:
        - identifier: home
          name: Merhaba 👋
          url: /
          weight: 1
        - identifier: posts
          name: Yazılar
          url: /yazilar/
          weight: 2
        - identifier: projects
          name: Projeler
          url: /projeler/
          weight: 3
        - identifier: til
          name: Bugün Öğrendim
          url: /bo/
          weight: 4
        - identifier: photographs
          name: Fotoğraflar
          url: /fotograflar/
          weight: 5
        # - identifier: dict
        #   name: Sözlük
        #   url: /sozluk/
        #   weight: 5
        # - identifier: links
        #   name: Yer İmleri
        #   url: /imler/
        #   weight: 7
        # - identifier: tags
        #   name: Etiketler
        #   url: /etiketler/
        #   weight: 8
        - identifier: rss
          name: RSS
          url: /index.xml
          weight: 9
    permalinks:
      posts: ":filename/"
      dict: "sozluk/:sections[1:]/:filename/"
      til: "bo-:filename/"
      projects: "proje-:sections[1:]-:filename/"
      photographs: "fotograf-:filename/"
      links: "imler/:filename/"
      tags: "etiketler/:slug/"

taxonomies:
  tag: tags

imaging:
  quality: 99

params:
  cdnUrl: https://cdn.ahmt.me
  footer:
  # For more date layouts see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts
  dateLayout: ":date_long"
  katex: false
  search: true
  moveFooterToHeader: false
  logoAlt: ahmt.me
  showLangSwitchAlways: false
  showPostSummaries: false
  enableRobotsTXT: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

build:
  buildStats:
    enable: true
  cachebusters:
    - source: hugo_stats.json
      target: css
    - source: tailwind.config.js
      target: css
